### PR TITLE
fix upscroll styling on mobile

### LINKED ISSUE #215: address upscroll wonkiness on beeswarm
On mobile, the upscroll for the beeswarm gets off in the transition between the 100% training ANN data and the RMSE dot that moves around. The links from the error chart appear early (`step_rmse+3`) when they shouldn't be seen until `step_error_obs`, and may have their own strength that's counteracting `forceCollide`? It's possible this is simply due to a step numbering issue on mobile, where the forces are changing out of sync with the data in view.

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
* Fix upscroll chartStates for `step_rmse` section and `step_error_obs` on mobile
* Fix upscroll chartStates for `step_rmse` on desktop (initial rmse dot wasn't centered on upscroll)

Closes #215 

Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

File: src/views/2-Modeling/Modeling.vue [hunk 1]
```diff
@@ -1738,13 +1740,13 @@
...
-          if (response.direction == "up" && this.step === this.step_rmse) {
+          if (response.direction == "up" && this.step <= this.step_rmse+2) {
             this.chartState.strengthy = 1.5;
             this.chartState.strengthy = 2;
             this.chartState.radius = 0;
              this.chartState.strengthr = 0;
-             this.chartState.alpha = .2;
-             this.chartState.aDecay = 0.15;
+             this.chartState.alpha = 1;
+             this.chartState.aDecay = 0.1;
```
Comment (cnell-usgs) [inline src/views/2-Modeling/Modeling.vue:1749]: ok yeah this makes sense to be different on the upscroll. needs more energy to get them to the right place. also looks like the `===` might have been limiting which steps applied to. nice fix!

**Review by cnell-usgs — APPROVED** [review]
